[package]
name = "theist"
version = "0.3.0"
edition = "2021"

[dependencies]
bytes = "1.3.0"
image = "0.24.5"
regex = "1.7.0"
iced = { version = "0.8.0", features = ["image"] }
iced_native = "0.9.1"
rfd = "0.10.0"
libflate = "1.2.0"
