[package]
name = "theist"
version = "0.3.0"
edition = "2021"

[dependencies]
bytes = "1.3.0"
image = "0.24.5"
regex = "1.7.0"
iced = { version = "0.7.0", features = ["image"] }
rfd = "0.10.0"
libflate = "1.2.0"
